name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2 || >=20.9.0'

      - name: Install dependencies
        run: pnpm install

      - name: Run Build
        run: pnpm build
