name: CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.2 || >=20.9.0'

      - name: Start Postgres
        run: docker compose -f docker-compose.workflows.yml up -d

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_CONTENT }}" > .env

      - name: Run Build
        run: pnpm prod-build

      - name: Stop and clean up
        run: docker compose down
